# If the application explicitly says it doesn't want to use any orm,
# then we're not going to initialize any default orm.
# Note: this is initialization process only. By the default, application
# generated by mack still have data_mapper as default.
orm = app_config.orm
unless orm.nil? 
  Mack.logger.info "Initializing #{orm} orm..."
  require "mack-#{orm}"
  require "mack-#{orm}_tasks"
end