require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require File.join(File.dirname(__FILE__), "..", "..", "lib", "mack_tasks")
require(File.join(File.dirname(__FILE__), "..", "..", "lib", 'mack'))
